# Local Development Configuration
# This file contains local-specific overrides for development

spring:
  r2dbc:
    url: r2dbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DB:weatherdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DB:weatherdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DB:weatherdb}
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  cache:
    redis:
      time-to-live: 300s # 5 minutes for faster development feedback

# Local-specific logging
logging:
  level:
    com.lplemos.weather_service: DEBUG
    org.springframework.r2dbc: DEBUG
    org.flywaydb: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG

# Local development configuration
# This file should NEVER be committed to Git
# Copy this file and add your actual API key

weather:
  openweathermap:
    api-key: ${WEATHER_OPENWEATHERMAP_API_KEY:}
    base-url: https://api.openweathermap.org/data/2.5
    units: metric
    language: en

# Override any other settings for local development if needed 